# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ed678598caec3e92bebe949f1d279b2b3c281d3150b13bd04452207f0c8cef815c57cf1fa042919ab204d8230295733a4b530d530e5b0c6382203d2029b4774

test:
  secret_key_base: 9678286ac03e9426242e6f8015b59a91d7bf4638c6459565d569f55eec626d1c8581bb61d8d8b9f1382ccf8a821e03cda72ccbb6dc22dc5fcd1811496755f226

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
